locking/local_lock: Include missing <linux/irqflags.h>
Include <linux/local_lock.h> into an empty TU will result in the compiler
complaining:

./include/linux/local_lock.h: In function ‘class_local_lock_irqsave_constructor’:
./include/linux/local_lock_internal.h:95:17: error: implicit declaration of function ‘local_irq_save’; <...>
   95 |                 local_irq_save(flags);                          \
      |                 ^~~~~~~~~~~~~~

Include <linux/irqflags.h> to allow including local_lock.h where irqflags.h is
not otherwise included.

Signed-off-by: Marco Elver <elver@google.com>